### ISSUE TITLE
1.1.0 & 1.2.0 Cors Error

### ISSUE THREAD

**Issue by Burnsy** [redwoodjs/redwood#5344]
After upgrading from 1.0.0 to 1.1.0 or 1.2.0 it causes our webside now have cors problems. 

Before this we did not have any cors problems

![CleanShot 2022-04-27 at 10 48 24](https://user-images.githubusercontent.com/15834048/165491973-7b4943ae-a519-4889-979e-08d9dec0e948.png)

![CleanShot 2022-04-27 at 10 48 58](https://user-images.githubusercontent.com/15834048/165492026-fea595cc-f54e-457a-b775-63fd1d9cd52f.png)

```jsx

graphql.ts
export const handler = createGraphQLHandler({
  loggerConfig: {
    logger,
    options: {
      tracing: true,
      operationName: true,
      requestId: true,
      query: true,
    },
  },
  getCurrentUser,
  directives,
  sdls: schemas,
  services,
  context: setContext,
  cors: {
    origin: [
      'https://dashboard.everfund.io',
    ],
    credentials: true,
  },
  // extraPlugins,
  onException: () => {
    // Disconnect from your database with an unhandled exception.
    db.$disconnect()
  },
})

React Query Provider
const useGraphqlClient = () => {
  const { uri } = useFetchConfig()
  const graphqlClient = new GraphQLClient(uri, {
    // credentials: 'include',
    mode: 'no-cors',
  })
  return graphqlClient
}
```

This could be a my problem? as our next.js website works and passes cors, its just our redwood dashboard using react-query provider does not. maybe i got the mode wrong or something. 

I just found it weird it worked on 1.0.0 but since not.

**Comment by thedavidprice** [comment]
I think the `access-control-allow-origin: *` is the key — that should be a specific domain, I believe. Where are you setting that? 

My guess is react query related. Are you correctly configured in your App.tsx file? E.g. 
https://github.com/redwoodjs/deploy-target-ci/blob/main/serverless-aws/web/src/App.tsx

**Comment by Burnsy** [comment]
just checked my production requests. 

![CleanShot 2022-04-28 at 11 08 17](https://user-images.githubusercontent.com/15834048/165730108-442398b5-1dfe-4ec4-b94c-24dba5e8af3c.png)

It looks like in the 1.1.0 and 1.2.0 it automatically sends a `access-control-allow-origin: *` back to the client without the correct url. 

There must be a breaking change in RW.

**Comment by thedavidprice** [comment]
Could you confirm whether or not you're seeing similar behavior for this site (deployed on Flightcontrol)?
https://d2dub2qmgsm5yj.cloudfront.net

It's still unclear to me which hosting provider you're using. 

Also, to confirm, you have a Next client that is working but the Redwood Web client is not, correct?

Lastly, I had the same issue with `access-control-allow-origin: *` in our Serverless AWS deploy. What was missing was AWS API Gateway config here:
https://github.com/redwoodjs/deploy-target-ci/blob/main/serverless-aws/api/serverless.yml

**Comment by Burnsy** [comment]
So we are self hosting with pm2 baremetal. has @cannikin ran into this problem.

Yeah am seeing similar behavior on that cloudfront website

![CleanShot 2022-04-29 at 9 17 09](https://user-images.githubusercontent.com/15834048/165908568-04223caf-d922-495a-a196-124554dddc0c.png)

Just to confirm, updated from 1.0.0 to 1.1.0 or 1.2.0 no other changes and we now get CORS problems. Self hosted on PM2 with nginx. 

And this is my browser
https://www.whatismybrowser.com/w/ENZCYT8

**Comment by Burnsy** [comment]
i believe in the test yes it was working. but that makes it more confusing!

**Comment by cannikin** [comment]
Looking at that browser error, it seems like an absolute vs. relative URL problem: the error says it's coming from a Cloudfront server, but shouldn't that be your Redwood API? It's saying that `https://d14jmar3pzcfvh.cloudfront.net/graphql` is returning the '*' header (which it might be, I'm not sure how Cloudfront headers are configured by default). But a request to `/graphql` shouldn't be going to Cloudfront, that should be `api.everfund.io/graphql` right?

Maybe `API_URL` isn't an absolute URL in redwood.toml? Something like it's going to just `/` instead of `https://api.everfund.io` maybe?

And it could be that somewhere between 1.0.0 and 1.1.1 there was a change in behavior to how that variable is resolved into an absolute URL?

**Comment by mabadir** [comment]
Hi All,
I can confirm this issue has hit other Flightcontrol customers. I am up to help on that, any thoughts of where to look for the issue?

**Comment by mabadir** [comment]
Hello @cannikin, in the test Flightcontrol app, we have it as a single value, but still not working:
https://github.com/redwoodjs/deploy-target-ci/blob/5b681dc58e4e2e9f1d2c617e5573295ad9f50833/flightcontrol/api/src/functions/graphql.ts#L22

> Can you try changing your `origin` to be just a string, instead of an array of strings?
> 
> ```
> cors: {
>   origin: 'https://dashboard.everfund.io',
> },
> ```

**Comment by dac09** [comment]
Hey both! Thanks for reporting this - I suspect this is a change downstream in one of the yoga dependencies. I’ll take a look tomorrow and post some tips on where to look as well if I can’t see an obvious solution.
